server:
  port: 9000

#屏蔽数据源配置
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true  #允许bean定义信息重写